name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install make git cmake python3
          
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup VITASDK
      run: |
        export VITASDK=/usr/local/vitasdk
        export PATH=$VITASDK/bin:$PATH
        git clone https://github.com/vitasdk/vdpm
        cd vdpm
        ./bootstrap-vitasdk.sh
        ./install-all.sh
    
    - name: Build
      run: |
        export VITASDK=/usr/local/vitasdk
        export PATH=$VITASDK/bin:$PATH
        mkdir build && cd build && cmake ..
        make

    - uses: actions/upload-artifact@v4
      with:
        name: VITA-Homebrew-Sorter.vpk
        path: build/VITA-Homebrew-Sorter.vpk
